### ISSUE TITLE
Access to the paper

### ISSUE THREAD

**Issue by hugoabonizio** [jpposadas/FakeNewsCorpusSpanish#1]
Hi @jpposadas! Your FakeNewsCorpusSpanish is a really interesting dataset!

I'm researching on the field of fake news detection too and started to make some experiments with this corpus. I'd really enjoy reading your paper "Detection of Fake News in a New Corpus for the Spanish Language", but can't find it. Is it available anywhere? Is there a preprint version of it?

Best regards :smiley:

**Comment by jpposadas** [comment]
Hi @hugoabonizio!

The paper is now available on this page https://content.iospress.com/articles/journal-of-intelligent-and-fuzzy-systems/ifs179034

Best regards
