### ISSUE TITLE
Dataset available

### ISSUE THREAD

**Issue by yacosta738** [jpposadas/FakeNewsCorpusSpanish#2]
I am conducting an investigation for my master's degree on detecting false news in Spanish and I would very much like to be able to use your dataset since there are very few that contain a corpus of news in Spanish. Reading your article I got here but the dataset is gone. I wrote to him but I have not received any response. You think you can provide me with the dataset. Thank you

**Comment by jpposadas** [comment]
We apologize for any inconvenience. Since the corpus was used in the MEX-A3T competition, it was removed for a time.
Now the corpus is available and can be used to compare your proposals and as a antecedent to the task. Best regards.
